[package]
name = "git-switch"
version = "0.1.0"
authors = ["Ashik Meerankutty <ashik9591@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
